{{- $manualHTTPS := and .Values.mlhub.env.SSL_ENABLED (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and .Values.mlhub.env.SSL_ENABLED (eq .Values.proxy.https.type "secret") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
        {{- if .Values.proxy.labels }}
        {{- .Values.proxy.labels | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      annotations:
        # This lets us autorestart when the secret changes!
        checksum/hub-secret: {{ include (print $.Template.BasePath "/hub/secret.yaml") . | sha256sum }}
        checksum/proxy-secret: {{ include (print $.Template.BasePath "/proxy/secret.yaml") . | sha256sum }}
        {{- if .Values.proxy.annotations }}
        {{- .Values.proxy.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- /* if .Values.scheduling.podPriority.enabled  */}}
      #priorityClassName: {{ .Release.Name }}-default-priority
      {{- /* end  */}}
      nodeSelector: {{ toJson .Values.proxy.nodeSelector }}
      {{- include "jupyterhub.coreAffinity" . | nindent 6 }}
      {{- if $manualHTTPS }}
      volumes:
        - name: tls-secret
          secret:
            secretName: proxy-manual-tls
      {{- else if $manualHTTPSwithsecret }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ .Values.proxy.https.secret.name }}
      {{- end }}
      containers:
        - name: chp
          image: {{ .Values.proxy.chp.image.name }}:{{ .Values.proxy.chp.image.tag }}
          {{- if or $manualHTTPS $manualHTTPSwithsecret }}
          volumeMounts:
            - name: tls-secret
              # mountPath: /etc/chp/tls
              mountPath: /resources/ssl
              readOnly: true
          {{- end }}
          resources:
            {{- .Values.proxy.chp.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          securityContext:
            # Don't allow any process to execute as root inside the container
            allowPrivilegeEscalation: false
          env:
            - name: ADDITIONAL_ARGS
              {{- $args := "--ip=0.0.0.0 --api-ip=0.0.0.0 --api-port=8001 --port=8000 --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT) --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)/hub/error" }}
              {{- if .Values.mlhub.debug }}
              {{- $args = printf "%s %s" $args "--log-level=debug" }}
              {{- end }}
              value: {{ $args | quote }}
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hub-secret
                  key: proxy.token
            - name: EXECUTION_MODE
              value: "k8s"
            - name: SSHD_TARGET
              value: hub:22
            - name: START_SSH
              value: "false"
            - name: START_JHUB
              value: "false"
            - name: START_CHP
              value: "true"
            {{- if .Values.proxy.extraEnv }}
            {{- $extraEnvType := typeOf .Values.proxy.extraEnv }}
            {{- /* If we have a list, embed that here directly. This allows for complex configuration from configmap, downward API, etc. */}}
            {{- if eq $extraEnvType "[]interface {}" }}
            {{- .Values.proxy.extraEnv | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- else if eq $extraEnvType "map[string]interface {}" }}
            {{- /* If we have a map, treat those as key-value pairs. */}}
            {{- range $key, $value := .Values.proxy.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.mlhub.env }}
            {{- range $key, $value := .Values.mlhub.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.proxy.chp.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          ports:
            {{- if or $manualHTTPS $manualHTTPSwithsecret }}
            - containerPort: 8443
              name: proxy-https
            {{- end }}
            - containerPort: 8000
              name: proxy-public
            - containerPort: 8001
              name: api
          livenessProbe:
            httpGet:
              path: /_chp_healthz
              port: proxy-public
          readinessProbe:
            httpGet:
              path: /_chp_healthz
              port: proxy-public
