{{- $manualHTTPS := and .Values.mlhub.env.SSL_ENABLED (eq .Values.proxy.https.type "manual") -}}
{{- if $manualHTTPS -}}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-manual-tls
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.proxy.https.manual.cert | b64enc }}
  tls.key: {{ .Values.proxy.https.manual.key | b64enc }}
  cert.crt: {{ .Values.proxy.https.manual.cert | b64enc }}
  cert.key: {{ .Values.proxy.https.manual.key | b64enc }}
{{- end }}
